environment:
  my_version_number: 1.0.0          # DONT FORGET TO CHANGE IS IN THE ISS FILE
  application_name: ProjectEulerAnswers         # DONT FORGET TO CHANGE IS IN THE ISS FILE
  project_name: Euler

version: $(my_version_number).{build}

skip_tags: true

configuration: Release

before_build:
  - ps: nuget restore -Verbosity quiet

build_script:
  - gradlew.bat assemble --info --no-daemon -PbintrayUserName -PbintrayApiKey
  - msbuild "C:\projects\projecteuleranswers\$($env:project_name).sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

cache:
  - C:\Users\appveyor\.gradle

build:
  verbosity: minimal
  project: Euler.sln

for:
  - branches:
      only:
        - master

    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '$(my_version_number)'
      package_version: '$(my_version_number)'
      assembly_version: '$(my_version_number)'
      file_version: '$(my_version_number)'
      informational_version: '$(my_version_number)'

    after_test:
#      - ps: .\gradlew.bat assemble --info --no-daemon -PbintrayUserName -PbintrayApiKey
      - ps: dotnet publish "-p:PublishProfile=$($env:project_name).csproj" -c:Release -o:Publish\bin -v:m -r:win-x64   --self-contained:true -p:PublishSingleFile=false -p:PublishTrimmed=true
    #      - ps: '& "C:\Program Files (x86)\Inno Setup 6\iscc.exe" /qp "Inno Config.iss"'

    artifacts:
      - path: /Installer/$(application_name).exe
        name: WinInstaller

    deploy:
      - provider: GitHub
        release: $(my_version_number)
        auth_token: # encrypted token:
          secure: HESVuhwKdUbPpbBsQrWslB7GYNy5r03/MN/enpu7UWbY886bOE+EpbEFwAVMrtLO #REPLACE WITH TOKEN
        artifact: WinInstaller
        draft: false
        prerelease: false
        force_update: false
        on:
          branch: master