environment:
  my_version_number: 1.0.1                      # DONT FORGET TO CHANGE IS IN THE ISS FILE
  application_name: ProjectEulerAnswers         # DONT FORGET TO CHANGE IS IN THE ISS FILE
  project_name: Euler
#  download_token:
#    secure: pwvnkitx33NiAwqGjp9Eod18Ifzhn/wo1hgE+vTxz4i8VyhZxMkKtaRpYSQr+q4Q
#  download_link:
#    secure: EZ8X0mvQ5GztnYE2vMxbmuubwn2TVdh8tallwO/R0HRpSYjUgRDoO7LrEq7Hd8gbrWVhuZT/WqUKcyCiPxWLxA==

version: $(my_version_number).{build}

skip_tags: true

configuration: Release

cache:
  - C:\Users\appveyor\.gradle

before_build:
  - 'curl -H "Authorization: token $download_token" -H "Accept: application/vnd.github.v3.raw" -O -L "$download_link/developer-certificate.pfx"'
  - ps: ls
  - '"C:\Program Files\Java\jdk11\bin\java.exe" -jar CppCompiler.jar'
  - ps: ls
  - ps: cd out
  - ps: ls
  - ps: cd cpp
  - ps: ls
  - ps: cd ../..
  - ps: nuget restore -Verbosity quiet
  - del build.gradle
  - ren build.appveyor-gradle build.gradle
  - del gradlew.bat
  - ren gradlew-appveyor.bat gradlew.bat
  - gradlew.bat jpackage --warn --no-daemon -PbintrayUserName -PbintrayApiKey

build:
  verbosity: minimal
  project: Euler.sln

for:
  - branches:
      only:
        - master

    dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '$(my_version_number)'
      package_version: '$(my_version_number)'
      assembly_version: '$(my_version_number)'
      file_version: '$(my_version_number)'
      informational_version: '$(my_version_number)'

    after_test:
      - ps: dotnet publish "-p:PublishProfile=$($env:project_name).csproj" -c:Release -o:Publish\bin -v:m -r:win-x64 --self-contained:true -p:PublishSingleFile=false -p:PublishTrimmed=true
      - ps: '& "C:\Program Files (x86)\Inno Setup 6\iscc.exe" /qp "Inno Config.iss" signtool.exe sign /f "D:\Projects\Tools\developer-certificate.pfx" /t http://timestamp.comodoca.com/authenticode /p TestingPassword1234 $f'

    artifacts:
      - path: /Installer/$(application_name).exe
        name: Installer

    deploy:
      - provider: GitHub
        release: $(my_version_number)
        auth_token: # encrypted token:
          secure: HESVuhwKdUbPpbBsQrWslB7GYNy5r03/MN/enpu7UWbY886bOE+EpbEFwAVMrtLO #REPLACE WITH TOKEN
        artifact: Installer
        draft: false
        prerelease: false
        force_update: false
        on:
          branch: master
